[pytest]
testpaths = tests
filterwarnings =
    error::DeprecationWarning
    ignore::DeprecationWarning:starlette.testclient
    ignore:.*httpx.*starlette.testclient.*
    default
addopts = --strict-markers
